dist: focal
sudo: enabled

language:
    - c
addons:
  apt:
    packages:
    - valgrind
    - gcc
    - clang
    - python-docutils
    - python3-pip
    - python3-setuptools
    - ninja-build
    - meson
    - python3-pytest
    - libglib2.0-dev
install: test/travis-install.sh
script: test/travis-build.sh

